import { ChatService } from './service'
import { InteractionService } from '../interaction/service'
import express from 'express'

const whatsAppChatRouter = express.Router()
const chatService = new ChatService()
const interactionService = new InteractionService()

whatsAppChatRouter
  .post('/test', chatService.testTransaction.bind(chatService))
  .post('/', chatService.chatByWorkflow.bind(chatService))
  .post('/send-message', chatService.sendBotLivechatMessage.bind(chatService))
  .post('/chatCleanUp', chatService.chatCleanUp.bind(chatService))
  .get('/getServiceTypes', chatService.getServiceTypes.bind(chatService))
  .post('/get-tarrif-name', chatService.getTarrifName.bind(interactionService))
  .get('/getEnquiries', chatService.getEnquiries.bind(chatService))
  .get('/booster-plans', chatService.getBoosterPlans.bind(interactionService))
  .get('/getImagineGo', chatService.getImagineGo.bind(chatService))
  .post('/customer-exist', chatService.checkCustomerExistance.bind(chatService))
  .post('/whatsAppCustomerExistance', chatService.checkWhatsAppCustomerExistance.bind(chatService))// used in livechat-web as well as mobile
  .post('/customerLanguage', chatService.customerLanguage.bind(chatService))
  .post('/updateLanguage', chatService.updateLanguage.bind(chatService))
  .post('/interactions', chatService.customerInteractions.bind(chatService))
  .post('/inboundMsg', chatService.inboundMsg.bind(chatService))
  .post('/createHelpdeskTicket', chatService.createHelpdeskTicket.bind(chatService))
  .post('/updateHelpdeskTicket', chatService.updateHelpdeskTicket.bind(chatService))
  .post('/createCustomer', chatService.createCustomer.bind(chatService))
  .post('/updateCustomer', chatService.updateCustomer.bind(chatService))
  .post('/followUp', interactionService.addFollowUp.bind(interactionService))
  .post('/opendHelpdeskTickets', chatService.opendHelpdeskTickets.bind(interactionService))
  .post('/closedHelpdeskTickets', chatService.closedHelpdeskTickets.bind(interactionService))
  .post('/humanHandover', chatService.humanHandover.bind(interactionService))
  .post('/create-whatsapp-inquiry', chatService.createWhatsappInquiry.bind(interactionService))
  .post('/create-whatsapp-complaint', chatService.createWhatsappComplaint.bind(interactionService))
  .post('/delete-inbounds', chatService.deleteInbounds.bind(interactionService))
  .post('/delete-inbounds', chatService.deleteInbounds.bind(interactionService))
  .post('/createChat', chatService.createMobileChat.bind(chatService))
  .post('/create-chat', chatService.createChat.bind(interactionService))
  .post('/customer-registration', chatService.registration.bind(interactionService))
  .put('/update-socket-chat-bot/:id', chatService.updateBotChatSocket.bind(interactionService))
  .post('/validate-access-number', chatService.validateAccessNumber.bind(interactionService))
  .post('/validate-ic-number', chatService.validateIcNumber.bind(interactionService))
  .post('/get-customer-summary', chatService.getCustomerSummary.bind(interactionService))
  .post('/send-otp', chatService.sendOtp.bind(interactionService))
  .post('/validate-otp', chatService.validateOtp.bind(interactionService))
  .post('/add-balance', chatService.addBalance.bind(interactionService))
  .post('/getAgentInfo', chatService.getAgentInfo.bind(interactionService))
  .post('/get-chat-info', chatService.getChatInfo.bind(interactionService))
  .post('/update-chat', chatService.updateChat.bind(interactionService))
  .post('/update-chat-existing-customer', chatService.updateChatExistingCustomer.bind(interactionService))
module.exports = whatsAppChatRouter
