-- pharmacraft.access_no_max_equipd_id_3_mar_2023 definition


-- pharmacraft.address_lookup definition

-- Drop table

-- DROP TABLE pharmacraft.address_lookup;

CREATE TABLE pharmacraft.address_lookup (
	post_code varchar(10) NULL,
	adm_unit1 varchar(100) NULL,
	district varchar(100) NULL,
	status varchar(20) NULL,
	created_by int4 NULL,
	created_at timestamptz NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	block varchar(100) NULL,
	building_name varchar(100) NULL,
	state varchar(50) NULL,
	latitude varchar(20) NULL,
	longitude varchar(20) NULL,
	"zone" varchar(20) NULL,
	is_cust_addr bpchar(1) NULL,
	is_bill_addr bpchar(1) NULL,
	crm_addr_uid varchar NULL,
	sub_district varchar(100) NULL
);



CREATE TABLE pharmacraft.addressmap (
	auto_addressid varchar(32767) NULL,
	address_uid varchar(32767) NULL
);



-- pharmacraft.app_config definition

-- Drop table

-- DROP TABLE pharmacraft.app_config;

CREATE TABLE pharmacraft.app_config (
	app_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	app_name varchar(100) NULL,
	config jsonb NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL,
	image text NULL,
	CONSTRAINT app_config_pk PRIMARY KEY (app_id)
);



-- pharmacraft.attachments definition

-- Drop table

-- DROP TABLE pharmacraft.attachments;

CREATE TABLE pharmacraft.attachments (
	attachment_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	file_name varchar(500) NOT NULL,
	file_type varchar(500) NOT NULL,
	entity_type varchar(500) NOT NULL,
	entity_id varchar NOT NULL,
	"content" text NOT NULL,
	status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	CONSTRAINT attachments_pk PRIMARY KEY (attachment_id)
);

-- pharmacraft.business_entity definition

-- Drop table

-- DROP TABLE pharmacraft.business_entity;

CREATE TABLE pharmacraft.business_entity (
	code varchar(20) NOT NULL,
	description varchar(200) NOT NULL,
	code_type varchar(100) NOT NULL,
	mapping_payload jsonb NULL,
	status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT business_entity_pk PRIMARY KEY (code)
);


-- pharmacraft.customer_template definition

-- Drop table

-- DROP TABLE pharmacraft.customer_template;

CREATE TABLE pharmacraft.customer_template (
	title varchar(1000) NULL,
	first_name varchar(1000) NULL,
	last_name varchar(1000) NULL,
	gender varchar(1000) NULL,
	birth_date varchar(1000) NULL,
	id_type varchar(1000) NULL,
	id_value varchar(1000) NULL,
	customer_type varchar(1000) NULL,
	status varchar(1000) NULL,
	crm_customer_no varchar(1000) NULL,
	customer_category varchar(1000) NULL,
	customer_class varchar(1000) NULL,
	crm_address_id varchar(1000) NULL,
	address_type varchar(1000) NULL,
	hno varchar(1000) NULL,
	block varchar(1000) NULL,
	building_name varchar(1000) NULL,
	street varchar(1000) NULL,
	road varchar(1000) NULL,
	city varchar(1000) NULL,
	town varchar(1000) NULL,
	state varchar(1000) NULL,
	district varchar(1000) NULL,
	country varchar(1000) NULL,
	post_code varchar(1000) NULL,
	crm_contact_id varchar(1000) NULL,
	contact_type varchar(1000) NULL,
	contact_no varchar(1000) NULL,
	contact_no_pfx varchar(1000) NULL,
	alt_contact_no_1 varchar(1000) NULL,
	email varchar(1000) NULL,
	alt_email varchar(1000) NULL,
	address_insert_flag varchar(5) NULL,
	contact_insert_flag varchar(5) NULL,
	customer_insert_flag varchar(5) NULL,
	address_update_flag varchar(5) NULL,
	contact_update_flag varchar(5) NULL,
	customer_update_flag varchar(5) NULL,
	bcae_address_type varchar(100) NULL,
	bcae_customer_type varchar(100) NULL,
	bcae_customer_category varchar(100) NULL,
	bcae_customer_class varchar(100) NULL,
	bcae_contact_type varchar(100) NULL,
	bcae_id_type varchar(100) NULL,
	acc_contact_id int4 NULL
);


-- pharmacraft.email_template definition

-- Drop table

-- DROP TABLE pharmacraft.email_template;

CREATE TABLE pharmacraft.email_template (
	template_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	template_type varchar(25) NULL,
	locale varchar(5) NOT NULL,
	template_name varchar(100) NOT NULL,
	subject varchar(240) NOT NULL,
	body text NOT NULL,
	template_status varchar(25) NOT NULL,
	created_by varchar(100) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by varchar(100) NOT NULL,
	updated_at timestamptz NOT NULL,
	mapping_payload jsonb NULL,
	CONSTRAINT email_template_pkey PRIMARY KEY (template_id)
);


-- pharmacraft.exception_table definition

-- Drop table

-- DROP TABLE pharmacraft.exception_table;

CREATE TABLE pharmacraft.exception_table (
	identification_no varchar(100) NULL,
	connection_type varchar(100) NULL,
	status varchar(100) NULL,
	crm_customer_no varchar(100) NULL,
	crm_account_no varchar(100) NULL,
	plan_name varchar(100) NULL
);


-- pharmacraft.inbound_messages definition

-- Drop table

-- DROP TABLE pharmacraft.inbound_messages;

CREATE TABLE pharmacraft.inbound_messages (
	inbound_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	sms_message_sid varchar(500) NULL,
	num_media varchar(10) NULL,
	profile_name varchar(300) NULL,
	wa_id varchar(200) NULL,
	sms_status varchar(100) NULL,
	body text NULL,
	message_to varchar(100) NULL,
	message_from varchar(100) NULL,
	account_sid varchar(100) NULL,
	menu_item varchar(1000) NULL,
	menu_value varchar(5) NULL,
	created_at timestamptz NULL,
	status varchar(20) NULL,
	created_by int4 NULL,
	updated_at timestamptz NULL,
	updated_by int4 NULL,
	next_value varchar(30) NULL,
	flag varchar NULL,
	chat_source varchar(20) NULL,
	payload jsonb NULL
);



-- pharmacraft.notes definition

-- Drop table

-- DROP TABLE pharmacraft.notes;

CREATE TABLE pharmacraft.notes (
	notes_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	notes varchar(200) NOT NULL,
	status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	CONSTRAINT notes_pk PRIMARY KEY (notes_id)
);


-- pharmacraft.notifications definition

-- Drop table

-- DROP TABLE pharmacraft.notifications;

CREATE TABLE pharmacraft.notifications (
	notification_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email text NULL,
	mobile_no numeric(20) NULL,
	notification_type varchar(20) NULL,
	subject varchar(200) NOT NULL,
	body text NOT NULL,
	reference_id int4 NULL,
	created_at timestamptz NOT NULL,
	sent_at timestamptz NULL,
	status varchar(20) NOT NULL,
	retries int4 NULL,
	user_id int4 NULL,
	role_id int4 NULL,
	department_id varchar(100) NULL,
	"source" varchar(100) NULL,
	is_viewed bpchar(1) NULL DEFAULT 'N'::bpchar,
	markedusers jsonb NULL,
	updated_at timestamptz NULL,
	notify_created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT notification_id_pk PRIMARY KEY (notification_id)
);
CREATE INDEX notifications_department_id_idx ON pharmacraft.notifications USING btree (department_id);
CREATE INDEX notifications_email_idx ON pharmacraft.notifications USING btree (email);
CREATE INDEX notifications_mobile_no_idx ON pharmacraft.notifications USING btree (mobile_no);
CREATE INDEX notifications_role_id_idx ON pharmacraft.notifications USING btree (role_id);
CREATE INDEX notifications_status_idx ON pharmacraft.notifications USING btree (status);
CREATE INDEX notifications_user_id_idx ON pharmacraft.notifications USING btree (user_id);


-- pharmacraft.otp definition

-- Drop table

-- DROP TABLE pharmacraft.otp;

CREATE TABLE pharmacraft.otp (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	reference varchar(200) NULL,
	otp numeric(6) NULL,
	sent_at timestamptz NOT NULL,
	status varchar(20) NOT NULL,
	CONSTRAINT otp_id_pk PRIMARY KEY (id)
);


-- pharmacraft.transitions definition

-- Drop table

-- DROP TABLE pharmacraft.transitions;

CREATE TABLE pharmacraft.transitions (
	trans_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	trans_code varchar(20) NOT NULL,
	from_unit varchar(50) NOT NULL,
	from_role varchar(20) NOT NULL,
	to_unit varchar(50) NOT NULL,
	to_role varchar(20) NOT NULL,
	from_status varchar(20) NULL,
	to_status varchar(20) NOT NULL,
	task_mapping varchar(3000) NULL,
	trans_status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL
);


-- pharmacraft.type_code_lu definition

-- Drop table

-- DROP TABLE pharmacraft.type_code_lu;

CREATE TABLE pharmacraft.type_code_lu (
	code_type varchar(20) NOT NULL,
	code varchar(50) NOT NULL,
	description varchar(100) NOT NULL,
	status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT type_code_lu_pk PRIMARY KEY (code)
);


-- pharmacraft.user_tokens definition

-- Drop table

-- DROP TABLE pharmacraft.user_tokens;

CREATE TABLE pharmacraft.user_tokens (
	user_id varchar NULL,
	"token" text NULL,
	status varchar NULL,
	created_at timestamp NULL,
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	updated_at timestamp NULL
);


-- pharmacraft.userrole definition

-- Drop table

-- DROP TABLE pharmacraft.userrole;

CREATE TABLE pharmacraft.userrole (
	userid text NULL,
	email text NULL,
	rolename text NULL,
	roleshort text NULL
);



-- pharmacraft.whatsapp_chat_history definition

-- Drop table

-- DROP TABLE pharmacraft.whatsapp_chat_history;

CREATE TABLE pharmacraft.whatsapp_chat_history (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	report_id int4 NULL,
	from_msg varchar NULL,
	to_msg varchar NULL,
	message varchar NULL,
	"source" varchar NULL,
	status varchar(20) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NULL,
	updated_by int4 NULL,
	created_by int4 NOT NULL,
	CONSTRAINT whatsapp_chat_history_pk PRIMARY KEY (id)
);


-- pharmacraft.whatsapp_report definition

-- Drop table

-- DROP TABLE pharmacraft.whatsapp_report;

CREATE TABLE pharmacraft.whatsapp_report (
	report_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	whatsapp_number varchar(20) NULL,
	contact_number numeric(20) NULL,
	access_number varchar(20) NULL,
	service_type varchar NULL,
	status varchar(20) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NULL,
	updated_by int4 NULL,
	created_by int4 NOT NULL,
	end_at timestamptz NULL,
	CONSTRAINT whatsapp_report_pk PRIMARY KEY (report_id)
);


-- pharmacraft.whatsapp_report_dtl definition

-- Drop table

-- DROP TABLE pharmacraft.whatsapp_report_dtl;

CREATE TABLE pharmacraft.whatsapp_report_dtl (
	report_dtl_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	whatsapp_number varchar NULL,
	contact_number numeric NULL,
	access_number varchar NULL,
	intxn_id int4 NULL,
	report_id int4 NULL,
	service_type varchar NULL,
	status varchar(20) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NULL,
	updated_by int4 NULL,
	created_by int4 NOT NULL,
	end_at timestamptz NULL,
	created_date date NULL DEFAULT CURRENT_DATE,
	end_date date NULL DEFAULT CURRENT_DATE,
	CONSTRAINT whatsapp_report_dtl_pk PRIMARY KEY (report_dtl_id)
);


-- pharmacraft.whatsup_plan definition

-- Drop table

-- DROP TABLE pharmacraft.whatsup_plan;

CREATE TABLE pharmacraft.whatsup_plan (
	refill_profile_id varchar(100) NULL,
	ref_plan_code varchar(100) NULL,
	plan_name varchar(100) NULL,
	comm_pack_name varchar(100) NULL,
	plan_category varchar(100) NULL,
	package_category varchar(100) NULL,
	plan_type varchar(100) NULL,
	ocs_desc varchar(100) NULL,
	offer_id varchar(100) NULL,
	offer_type varchar(100) NULL,
	quota varchar(100) NULL,
	units varchar(100) NULL,
	prod_type varchar(100) NULL,
	network_type varchar(100) NULL,
	service_cls varchar(100) NULL,
	validity varchar(100) NULL,
	charge varchar(100) NULL,
	mrc varchar(100) NULL,
	nrc varchar(100) NULL,
	bandwidth varchar(100) NULL,
	contract varchar(100) NULL,
	plan_category_cd varchar(50) NULL,
	prod_cat_type_cd varchar(50) NULL
);


-- pharmacraft.workflow_defn_new definition

-- Drop table

-- DROP TABLE pharmacraft.workflow_defn_new;

CREATE TABLE pharmacraft.workflow_defn_new (
	workflow_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	interaction_type varchar(20) NULL,
	product_type varchar(20) NULL,
	wf_definition jsonb NOT NULL,
	status varchar(20) NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL,
	workflow_name varchar(200) NULL,
	CONSTRAINT workflow_defn_new_pk PRIMARY KEY (workflow_id)
);


-- pharmacraft.workflow_hdr definition

-- Drop table

-- DROP TABLE pharmacraft.workflow_hdr;

CREATE TABLE pharmacraft.workflow_hdr (
	wf_hdr_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	wf_defn_id int4 NOT NULL,
	entity varchar(100) NOT NULL,
	entity_id varchar(200) NOT NULL,
	next_activity_id varchar(100) NULL,
	next_task_id varchar(100) NULL,
	wf_context jsonb NOT NULL,
	wf_status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL,
	created_date date NULL DEFAULT CURRENT_DATE,
	CONSTRAINT wf_hdr_pk PRIMARY KEY (wf_hdr_id)
);


-- pharmacraft.workflow_mapping definition

-- Drop table

-- DROP TABLE pharmacraft.workflow_mapping;

CREATE TABLE pharmacraft.workflow_mapping (
	mapping_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	mapping_name varchar NULL,
	"module" varchar NULL,
	workflow_id int4 NULL,
	"mapping" jsonb NULL,
	status varchar NULL,
	created_by int4 NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	updated_by int4 NULL
);



-- pharmacraft.users definition

-- Drop table

-- DROP TABLE pharmacraft.users;

CREATE TABLE pharmacraft.users (
	user_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	contact_no numeric NOT NULL,
	email varchar(100) NULL,
	user_type varchar(20) NOT NULL,
	photo varchar(100) NULL,
	title varchar(10) NULL,
	first_name varchar(100) NOT NULL,
	last_name varchar(100) NOT NULL,
	gender varchar(10) NULL,
	dob date NULL,
	office_no numeric NULL,
	extn numeric NULL,
	loginid varchar(100) NULL,
	notification_type varchar(10) NULL,
	bi_access bpchar(1) NOT NULL DEFAULT 'N'::bpchar,
	wa_access bpchar(1) NOT NULL DEFAULT 'N'::bpchar,
	login_password varchar(100) NOT NULL,
	status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	mapping_payload jsonb NULL,
	invite_token varchar(500) NULL,
	ic_number varchar(20) NULL,
	profile_picture text NULL,
	"location" varchar(100) NULL,
	one_time_password varchar(100) NULL,
	country varchar NULL,
	crm_user_id varchar(20) NULL,
	email_old varchar(200) NULL,
	login_attempts int4 NULL,
	admin_remark varchar(4000) NULL,
	activation_date date NULL,
	expiry_date date NULL,
	CONSTRAINT users_pk PRIMARY KEY (user_id),
	CONSTRAINT users_fk_status FOREIGN KEY (status) REFERENCES pharmacraft.business_entity(code)
);
CREATE INDEX users_email_idx ON pharmacraft.users USING btree (email);
CREATE INDEX users_loginid_idx ON pharmacraft.users USING btree (loginid);


-- pharmacraft.workflow_definition definition

-- Drop table

-- DROP TABLE pharmacraft.workflow_definition;

CREATE TABLE pharmacraft.workflow_definition (
	workflow_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	interaction_type varchar(20) NOT NULL,
	product_type varchar(20) NOT NULL,
	wf_definition jsonb NOT NULL,
	status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT workflow_definition_pk PRIMARY KEY (workflow_id),
	CONSTRAINT wf_def_fk_intxn_type FOREIGN KEY (interaction_type) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT wf_def_fk_prod_type FOREIGN KEY (product_type) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT wf_def_fk_status FOREIGN KEY (status) REFERENCES pharmacraft.business_entity(code)
);


-- pharmacraft.workflow_txn definition

-- Drop table

-- DROP TABLE pharmacraft.workflow_txn;

CREATE TABLE pharmacraft.workflow_txn (
	wf_txn_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	wf_hdr_id int4 NOT NULL,
	activity_id varchar(100) NULL,
	task_id varchar(100) NULL,
	wf_txn_status varchar(20) NOT NULL,
	txn_context jsonb NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL,
	curr_user int4 NULL,
	curr_entity varchar(100) NULL,
	curr_role int4 NULL,
	user_status varchar(20) NULL,
	from_user int4 NULL,
	from_entity varchar NULL,
	from_role int4 NULL,
	from_user_status varchar NULL,
	payload jsonb NULL,
	CONSTRAINT wf_txn_pk PRIMARY KEY (wf_txn_id),
	CONSTRAINT workflow_txn_fk FOREIGN KEY (wf_txn_status) REFERENCES pharmacraft.business_entity(code)
);


-- pharmacraft.address definition

-- Drop table

-- DROP TABLE pharmacraft.address;

CREATE TABLE pharmacraft.address (
	address_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	address_type varchar(20) NOT NULL,
	hno varchar(20) NOT NULL,
	block varchar(100) NULL,
	building_name varchar(100) NULL,
	street varchar(50) NOT NULL,
	road varchar(50) NOT NULL,
	city varchar(50) NOT NULL,
	town varchar(100) NOT NULL,
	state varchar(50) NULL,
	district varchar(50) NOT NULL,
	country varchar(50) NOT NULL,
	latitude varchar(20) NULL,
	longitude varchar(20) NULL,
	post_code varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	"zone" varchar(20) NULL,
	is_cust_addr bpchar(1) NULL DEFAULT 'N'::bpchar,
	is_bill_addr bpchar(1) NULL DEFAULT 'N'::bpchar,
	crm_addr_uid varchar NULL,
	migration_date timestamp NULL,
	migration_table varchar(40) NULL,
	migration_remarks varchar(500) NULL,
	validation_data varchar(20) NULL,
	crm_customer_id varchar(50) NULL,
	crm_account_id int4 NULL,
	CONSTRAINT address_pk PRIMARY KEY (address_id),
	CONSTRAINT address_fk_created_by FOREIGN KEY (created_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT address_fk_updated_by FOREIGN KEY (updated_by) REFERENCES pharmacraft.users(user_id)
);
CREATE INDEX address_crm_addr_uid_idx ON pharmacraft.address USING btree (crm_addr_uid);


-- pharmacraft.business_units definition

-- Drop table

-- DROP TABLE pharmacraft.business_units;

CREATE TABLE pharmacraft.business_units (
	unit_id varchar(100) NOT NULL,
	unit_name varchar(100) NOT NULL,
	unit_desc varchar(100) NOT NULL,
	unit_type varchar(100) NULL,
	parent_unit varchar(100) NULL,
	contact_id int4 NULL,
	address_id int4 NULL,
	status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL,
	mapping_payload jsonb NULL,
	mapping_payload_old json NULL,
	CONSTRAINT business_units_pk PRIMARY KEY (unit_id),
	CONSTRAINT business_units_created_fk FOREIGN KEY (created_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT business_units_fk_status FOREIGN KEY (status) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT business_units_mod_fk FOREIGN KEY (updated_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT business_units_parent_fk FOREIGN KEY (parent_unit) REFERENCES pharmacraft.business_units(unit_id) ON DELETE RESTRICT
);


-- pharmacraft.contacts definition

-- Drop table

-- DROP TABLE pharmacraft.contacts;

CREATE TABLE pharmacraft.contacts (
	contact_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title varchar(20) NULL,
	first_name varchar(500) NOT NULL,
	last_name varchar(500) NULL,
	contact_type varchar(10) NOT NULL,
	contact_no numeric NOT NULL,
	contact_no_pfx numeric NULL,
	alt_contact_no1 numeric NULL,
	alt_contact_no2 numeric NULL,
	email varchar(100) NULL,
	alt_email varchar(100) NULL,
	status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	crm_contact_id int4 NULL,
	migration_date timestamp NULL,
	migration_table varchar(40) NULL,
	migration_remarks varchar(500) NULL,
	validation_data varchar(20) NULL,
	service_number varchar(30) NULL,
	crm_customer_id varchar(50) NULL,
	crm_account_id int4 NULL,
	CONSTRAINT contacts_pk PRIMARY KEY (contact_id),
	CONSTRAINT contacts_create_fk FOREIGN KEY (created_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT contacts_mod_fk FOREIGN KEY (updated_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT contacts_statusfk FOREIGN KEY (status) REFERENCES pharmacraft.business_entity(code) ON DELETE RESTRICT
);


-- pharmacraft.customers definition

-- Drop table

-- DROP TABLE pharmacraft.customers;

CREATE TABLE pharmacraft.customers (
	customer_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title varchar(20) NULL,
	first_name varchar(500) NOT NULL,
	last_name varchar(500) NULL,
	gender bpchar(1) NULL,
	birth_date date NULL,
	registered_no varchar(20) NULL,
	id_type varchar(10) NULL,
	id_value varchar(20) NULL,
	contact_id int4 NOT NULL,
	cust_type varchar(20) NOT NULL,
	donotemail bpchar(1) NULL DEFAULT 'Y'::bpchar,
	status varchar(20) NOT NULL,
	crm_customer_no varchar(20) NULL,
	customer_cat varchar(20) NULL,
	customer_class varchar(20) NULL,
	address_id int4 NULL,
	priority varchar(100) NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	reg_date date NULL,
	migration_date timestamp NULL,
	migration_table varchar(40) NULL,
	migration_remarks varchar(500) NULL,
	validation_data varchar(20) NULL,
	chat_language varchar(30) NULL,
	CONSTRAINT customers_pk PRIMARY KEY (customer_id),
	CONSTRAINT customers_fk FOREIGN KEY (status) REFERENCES pharmacraft.business_entity(code) ON DELETE RESTRICT,
	CONSTRAINT customers_fk_address_id FOREIGN KEY (address_id) REFERENCES pharmacraft.address(address_id),
	CONSTRAINT customers_fk_contact_id FOREIGN KEY (contact_id) REFERENCES pharmacraft.contacts(contact_id),
	CONSTRAINT customers_fk_created_by FOREIGN KEY (created_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT customers_fk_cust_type FOREIGN KEY (cust_type) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT customers_fk_customer_cat FOREIGN KEY (customer_cat) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT customers_fk_customer_class FOREIGN KEY (customer_class) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT customers_fk_id_type FOREIGN KEY (id_type) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT customers_fk_updated_by FOREIGN KEY (updated_by) REFERENCES pharmacraft.users(user_id)
);
CREATE INDEX customers_address_id_idx ON pharmacraft.customers USING btree (address_id);
CREATE INDEX customers_contact_id_idx ON pharmacraft.customers USING btree (contact_id);
CREATE UNIQUE INDEX customers_crm_customer_no_idx ON pharmacraft.customers USING btree (crm_customer_no);

-- pharmacraft.leads definition

-- Drop table

-- DROP TABLE pharmacraft.leads;

CREATE TABLE pharmacraft.leads (
	lead_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cust_name varchar(50) NULL,
	cust_cat varchar(20) NULL,
	contact_no numeric NULL,
	email_id varchar(100) NULL,
	service_type varchar(20) NULL,
	product_enquired varchar(50) NULL,
	contact_preference varchar(20) NULL,
	remarks varchar(500) NULL,
	created_by int4 NULL,
	created_at timestamptz NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	CONSTRAINT leads_pk PRIMARY KEY (lead_id),
	CONSTRAINT leads_fk_contact_preference FOREIGN KEY (contact_preference) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT leads_fk_created_by FOREIGN KEY (created_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT leads_fk_cust_cat FOREIGN KEY (cust_cat) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT leads_fk_updated_by FOREIGN KEY (created_by) REFERENCES pharmacraft.users(user_id)
);


-- pharmacraft.roles definition

-- Drop table

-- DROP TABLE pharmacraft.roles;

CREATE TABLE pharmacraft.roles (
	role_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	role_name varchar(100) NOT NULL,
	role_desc varchar(100) NOT NULL,
	is_admin varchar(100) NULL,
	parent_role int4 NULL,
	status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL,
	mapping_payload jsonb NULL,
	CONSTRAINT roles_pk PRIMARY KEY (role_id),
	CONSTRAINT roles_fk FOREIGN KEY (created_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT roles_fk_1 FOREIGN KEY (updated_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT roles_fk_2 FOREIGN KEY (status) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT roles_fk_3 FOREIGN KEY (parent_role) REFERENCES pharmacraft.roles(role_id)
);


-- pharmacraft.screen_module_mapping definition

-- Drop table

-- DROP TABLE pharmacraft.screen_module_mapping;

CREATE TABLE pharmacraft.screen_module_mapping (
	scr_mod_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	module_name varchar(50) NOT NULL,
	screen_name varchar(50) NOT NULL,
	api varchar(300) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	"method" varchar(50) NULL,
	"[method]" varchar(50) NULL,
	status varchar(10) NULL,
	CONSTRAINT scr_mod_pk PRIMARY KEY (scr_mod_id),
	CONSTRAINT screen_module_mapping_fk_created_by FOREIGN KEY (created_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT screen_module_mapping_fk_updated_by FOREIGN KEY (updated_by) REFERENCES pharmacraft.users(user_id)
);


-- pharmacraft.security_question definition

-- Drop table

-- DROP TABLE pharmacraft.security_question;

CREATE TABLE pharmacraft.security_question (
	profile_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	profile_name varchar(50) NULL,
	profile_value varchar(100) NULL,
	ref_id int4 NULL,
	created_by int4 NOT NULL DEFAULT 1,
	created_at timestamptz(0) NOT NULL DEFAULT '2021-05-03 00:00:00+05:30'::timestamp with time zone,
	updated_by int4 NOT NULL DEFAULT 1,
	updated_at timestamptz(0) NOT NULL DEFAULT '2021-05-03 00:00:00+05:30'::timestamp with time zone,
	CONSTRAINT security_question_pk PRIMARY KEY (profile_id),
	CONSTRAINT security_question_fk_created_by FOREIGN KEY (created_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT security_question_fk_updated_by FOREIGN KEY (updated_by) REFERENCES pharmacraft.users(user_id)
);



-- pharmacraft.user_session definition

-- Drop table

-- DROP TABLE pharmacraft.user_session;

CREATE TABLE pharmacraft.user_session (
	session_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id int4 NOT NULL,
	access_token jsonb NULL,
	payload jsonb NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NOT NULL,
	updated_at timestamptz NOT NULL,
	permissions jsonb NULL,
	curr_role varchar(100) NULL,
	curr_dept varchar(100) NULL,
	curr_role_id int4 NULL,
	curr_dept_id varchar(100) NULL,
	created_date date NULL DEFAULT CURRENT_DATE,
	CONSTRAINT user_session_pk PRIMARY KEY (session_id),
	CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES pharmacraft.users(user_id)
);


-- pharmacraft.accounts definition

-- Drop table

-- DROP TABLE pharmacraft.accounts;

CREATE TABLE pharmacraft.accounts (
	account_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	account_cat varchar(20) NOT NULL,
	account_class varchar(20) NOT NULL,
	account_priority varchar(20) NOT NULL,
	title varchar(20) NULL,
	first_name varchar(500) NOT NULL,
	last_name varchar(500) NULL,
	gender bpchar(1) NULL,
	birth_date date NULL,
	registered_no varchar(50) NULL,
	id_type varchar(20) NULL,
	id_value varchar(20) NULL,
	customer_id int4 NOT NULL,
	account_no int4 NULL,
	contact_id int4 NULL,
	address_id int4 NOT NULL,
	base_coll_plan varchar(50) NOT NULL,
	status varchar(20) NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	priority varchar(100) NULL,
	bill_lang varchar(10) NULL,
	bill_delivery_mthd varchar(10) NULL,
	no_of_copies numeric NOT NULL DEFAULT 1,
	reg_date date NULL,
	account_type varchar(20) NULL,
	sq_ref_id int4 NULL,
	crm_ref_id varchar(200) NULL,
	migration_date timestamp NULL,
	migration_table varchar(40) NULL,
	migration_remarks varchar(500) NULL,
	validation_data varchar(20) NULL,
	CONSTRAINT accounts_pk PRIMARY KEY (account_id),
	CONSTRAINT accounts_un UNIQUE (account_no),
	CONSTRAINT accounts_fk_account_priority FOREIGN KEY (account_priority) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT accounts_fk_address_id FOREIGN KEY (address_id) REFERENCES pharmacraft.address(address_id),
	CONSTRAINT accounts_fk_bill_lang FOREIGN KEY (bill_lang) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT accounts_fk_contact_id FOREIGN KEY (contact_id) REFERENCES pharmacraft.contacts(contact_id),
	CONSTRAINT accounts_fk_created_by FOREIGN KEY (created_by) REFERENCES pharmacraft.users(user_id),
	CONSTRAINT accounts_fk_customer_id FOREIGN KEY (customer_id) REFERENCES pharmacraft.customers(customer_id),
	CONSTRAINT accounts_fk_id_type FOREIGN KEY (id_type) REFERENCES pharmacraft.business_entity(code),
	CONSTRAINT accounts_fk_sq_red_id FOREIGN KEY (sq_ref_id) REFERENCES pharmacraft.security_question(profile_id),
	CONSTRAINT accounts_fk_updated_by FOREIGN KEY (updated_by) REFERENCES pharmacraft.users(user_id)
);
CREATE INDEX accounts_customer_id_idx ON pharmacraft.accounts USING btree (customer_id);
