import { aiosValidator } from './validation/request-data-validator'

const express = require('express')

const userRoute = require('./user/route')
const categoryRouter = require('./category/route')
const inventoryRouter = require('./inventory/route')
const poRouter = require('./purchase-orders/route')
const soRouter = require('./sale-orders/route')
const billingRouter = require('./billing/route')

const customerRoute = require('./customer/route')
const configRouter = require('./app-config/route')
const planRouter = require('./plan/route')
const dashboardRouter = require('./dashboard/route')
const organizationRouter = require('./organization/route')
const connectionRouter = require('./connection/route')
const accessNumberRouter = require('./access-number/route')
const lookupRouter = require('./lookup/route')
const mainRouter = express.Router()
const roleRouter = require('./role/route')
const attachmentRouter = require('./attachments/route')
const complaintsRouter = require('./complaints/route')
const campaignRouter = require('./campaign/route')
const serviceRequestRouter = require('./service-request/route')
const leadRouter = require('./lead/route')
const iccidRouter = require('./iccid/route')
const catalogRouter = require('./catalog/route')
const interactionRouter = require('./interaction/route')
const inquiryRouter = require('./inquiry/route')
const kioskRouter = require('./kiosk/route')
const workflowRouter = require('./workflow/route')
const businessParameterRouter = require('./business-parameters/route')
const notesRouter = require('./my-notes/route')
const notificationRouter = require('./notification/route')
const chatBoxRouter = require('./live-chat/route')
const ameyoRouter = require('./ameyo/route')
const reportRouter = require('./reports/route')
const workflowNewRouter = require('./workflow-new/route')
const webLiveChatRouter = require('./web-live-chat/route')
const whatsAppRouter = require('./whatsApp/route')
const companyRouter = require('./company/route')

mainRouter.use('/users', userRoute)
mainRouter.use('/category', categoryRouter)
mainRouter.use('/inventory', inventoryRouter)
mainRouter.use('/purchase-order', poRouter)
mainRouter.use('/sale-orders', soRouter)
mainRouter.use('/billing', billingRouter)
mainRouter.use('/company', companyRouter)

mainRouter.use('/customer', customerRoute)
mainRouter.use('/config', configRouter)
mainRouter.use('/plans', planRouter)
mainRouter.use('/dashboard', dashboardRouter)
mainRouter.use('/organization', organizationRouter)
mainRouter.use('/connection/service', connectionRouter)
mainRouter.use('/accessNumber', accessNumberRouter)
mainRouter.use('/lookup', lookupRouter)
mainRouter.use('/role', roleRouter)
mainRouter.use('/attachment', attachmentRouter)
mainRouter.post('/poc', aiosValidator)
mainRouter.use('/complaint', complaintsRouter)
mainRouter.use('/campaign', campaignRouter)
mainRouter.use('/service-request', serviceRequestRouter)
mainRouter.use('/lead', leadRouter)
mainRouter.use('/iccid', iccidRouter)
mainRouter.use('/catalog', catalogRouter)
mainRouter.use('/interaction', interactionRouter)
mainRouter.use('/inquiry', inquiryRouter)
mainRouter.use('/kiosk', kioskRouter)
mainRouter.use('/workflow', workflowRouter)
mainRouter.use('/business-parameter', businessParameterRouter)
mainRouter.use('/notes', notesRouter)
mainRouter.use('/notification', notificationRouter)
mainRouter.use('/live-chat', chatBoxRouter)
mainRouter.use('/ameyo', ameyoRouter)
mainRouter.use('/reports', reportRouter)
mainRouter.use('/workflow-new', workflowNewRouter)
mainRouter.use('/web-live-chat', webLiveChatRouter)
mainRouter.use('/whatsapp', whatsAppRouter)

module.exports = mainRouter
