const express = require('express')
const userRoute = require('./user/route')
const categoryRouter = require('./category/route')
const inventoryRouter = require('./inventory/route')
const poRouter = require('./purchase-orders/route')
const soRouter = require('./sale-orders/route')
const billingRouter = require('./billing/route')
const configRouter = require('./app-config/route')
const organizationRouter = require('./organization/route')
const lookupRouter = require('./lookup/route')
const mainRouter = express.Router()
const roleRouter = require('./role/route')
const businessParameterRouter = require('./business-parameters/route')
const notesRouter = require('./my-notes/route')
const notificationRouter = require('./notification/route')
const companyRouter = require('./company/route')
const paymentsRouter = require('./payments/route')
const workflowRouter = require('./workflow/route')
const workflowNewRouter = require('./workflow-new/route')
const reportsRouter = require('./reports/route')



mainRouter.use('/users', userRoute)
mainRouter.use('/category', categoryRouter)
mainRouter.use('/inventory', inventoryRouter)
mainRouter.use('/purchase-order', poRouter)
mainRouter.use('/sale-orders', soRouter)
mainRouter.use('/billing', billingRouter)
mainRouter.use('/payments', paymentsRouter)
mainRouter.use('/company', companyRouter)
mainRouter.use('/config', configRouter)
mainRouter.use('/organization', organizationRouter)
mainRouter.use('/lookup', lookupRouter)
mainRouter.use('/role', roleRouter)
mainRouter.use('/business-parameter', businessParameterRouter)
mainRouter.use('/notes', notesRouter)
mainRouter.use('/notification', notificationRouter)
mainRouter.use('/workflow', workflowRouter)
mainRouter.use('/workflow-new', workflowNewRouter)
mainRouter.use('/reports', reportsRouter)

module.exports = mainRouter